apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-component
    app.kubernetes.io/part-of: ostree-builder
  name: my-componentdb3g
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: my-component
    weight: 100
status: {}
